"""empty message

Revision ID: 118ac18a0bbb
Revises: e599f929b90
Create Date: 2015-01-22 14:07:28.776790

"""

# revision identifiers, used by Alembic.
revision = '118ac18a0bbb'
down_revision = 'e599f929b90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'from_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('from_id', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
