"""empty message

Revision ID: 13c68a154d16
Revises: 553527f880bc
Create Date: 2015-01-22 23:00:29.917317

"""

# revision identifiers, used by Alembic.
revision = '13c68a154d16'
down_revision = '553527f880bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'img_url')
    ### end Alembic commands ###
