"""empty message

Revision ID: 147821858091
Revises: 2ac8fc4943b6
Create Date: 2015-01-22 14:00:18.969544

"""

# revision identifiers, used by Alembic.
revision = '147821858091'
down_revision = '2ac8fc4943b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
