"""empty message

Revision ID: 18483888126
Revises: 20312378cead
Create Date: 2015-01-22 11:18:02.647730

"""

# revision identifiers, used by Alembic.
revision = '18483888126'
down_revision = '20312378cead'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), server_default="nextval('posts_id_seq'::regclass)", nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'posts_pkey')
    )
    ### end Alembic commands ###
