"""empty message

Revision ID: 19991b950bc2
Revises: 18483888126
Create Date: 2015-01-22 11:55:59.790863

"""

# revision identifiers, used by Alembic.
revision = '19991b950bc2'
down_revision = '18483888126'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points')
    ### end Alembic commands ###
