"""empty message

Revision ID: 20312378cead
Revises: 35163901d2bc
Create Date: 2014-10-31 11:48:41.600736

"""

# revision identifiers, used by Alembic.
revision = '20312378cead'
down_revision = '35163901d2bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
