"""empty message

Revision ID: 2599713fe6a0
Revises: 2c73165896de
Create Date: 2015-01-22 12:43:30.311044

"""

# revision identifiers, used by Alembic.
revision = '2599713fe6a0'
down_revision = '2c73165896de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
