"""empty message

Revision ID: 2a6adb4515be
Revises: 2599713fe6a0
Create Date: 2015-01-22 12:54:09.110594

"""

# revision identifiers, used by Alembic.
revision = '2a6adb4515be'
down_revision = '2599713fe6a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'created_at')
    ### end Alembic commands ###
