"""empty message

Revision ID: 2ac8fc4943b6
Revises: 503b1cce1bc1
Create Date: 2015-01-22 13:57:24.077275

"""

# revision identifiers, used by Alembic.
revision = '2ac8fc4943b6'
down_revision = '503b1cce1bc1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
