"""empty message

Revision ID: 2c73165896de
Revises: 58c1ef6a30c7
Create Date: 2015-01-22 12:37:19.955893

"""

# revision identifiers, used by Alembic.
revision = '2c73165896de'
down_revision = '58c1ef6a30c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
