"""empty message

Revision ID: 32bfb06d6b9a
Revises: 7ed3d04d76c
Create Date: 2015-01-22 14:17:35.507651

"""

# revision identifiers, used by Alembic.
revision = '32bfb06d6b9a'
down_revision = '7ed3d04d76c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False))
    ### end Alembic commands ###
