"""empty message

Revision ID: 35163901d2bc
Revises: 421fefb21a20
Create Date: 2014-10-22 18:40:00.322871

"""

# revision identifiers, used by Alembic.
revision = '35163901d2bc'
down_revision = '421fefb21a20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
