"""empty message

Revision ID: 3b3e99eda58f
Revises: 40410078c01b
Create Date: 2015-02-11 10:30:17.924887

"""

# revision identifiers, used by Alembic.
revision = '3b3e99eda58f'
down_revision = '40410078c01b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
