"""empty message

Revision ID: 40410078c01b
Revises: 44b154b57229
Create Date: 2015-02-11 10:29:08.872228

"""

# revision identifiers, used by Alembic.
revision = '40410078c01b'
down_revision = '44b154b57229'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('is_rand', sa.Boolean()))
    op.add_column('points', sa.Column('is_spent', sa.Boolean()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'is_spent')
    op.drop_column('points', 'is_rand')
    ### end Alembic commands ###
