"""empty message

Revision ID: 404a85753c9b
Revises: 118ac18a0bbb
Create Date: 2015-01-22 14:09:03.299513

"""

# revision identifiers, used by Alembic.
revision = '404a85753c9b'
down_revision = '118ac18a0bbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
