"""empty message

Revision ID: 44b154b57229
Revises: 45218bd774db
Create Date: 2015-02-11 10:27:15.542695

"""

# revision identifiers, used by Alembic.
revision = '44b154b57229'
down_revision = '45218bd774db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
