"""empty message

Revision ID: 45218bd774db
Revises: 13c68a154d16
Create Date: 2015-02-09 16:29:13.181103

"""

# revision identifiers, used by Alembic.
revision = '45218bd774db'
down_revision = '13c68a154d16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
