"""empty message

Revision ID: 54a2d38c2077
Revises: 2a6adb4515be
Create Date: 2015-01-22 13:11:40.423243

"""

# revision identifiers, used by Alembic.
revision = '54a2d38c2077'
down_revision = '2a6adb4515be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points_to_give', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points_to_give')
    ### end Alembic commands ###
