"""empty message

Revision ID: 55e951fd2d0f
Revises: 3b3e99eda58f
Create Date: 2015-02-11 11:04:41.548127

"""

# revision identifiers, used by Alembic.
revision = '55e951fd2d0f'
down_revision = '3b3e99eda58f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
