"""empty message

Revision ID: 58c1ef6a30c7
Revises: 19991b950bc2
Create Date: 2015-01-22 12:26:54.299873

"""

# revision identifiers, used by Alembic.
revision = '58c1ef6a30c7'
down_revision = '19991b950bc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
