"""empty message

Revision ID: 7ed3d04d76c
Revises: 404a85753c9b
Create Date: 2015-01-22 14:10:30.440845

"""

# revision identifiers, used by Alembic.
revision = '7ed3d04d76c'
down_revision = '404a85753c9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
