"""empty message

Revision ID: d85f18676b1
Revises: 252f0ad9d013
Create Date: 2015-01-22 14:25:56.272459

"""

# revision identifiers, used by Alembic.
revision = 'd85f18676b1'
down_revision = '252f0ad9d013'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
