"""empty message

Revision ID: e599f929b90
Revises: 147821858091
Create Date: 2015-01-22 14:05:28.845485

"""

# revision identifiers, used by Alembic.
revision = 'e599f929b90'
down_revision = '147821858091'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
